#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SummerOlympiads.Model.MySQL;

namespace SummerOlympiads.Model.MySQL	
{
	public partial class GoldMedalists : OpenAccessContext, IGoldMedalistsUnitOfWork
	{
		private static string connectionStringName = @"GoldmedalistsConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("GoldMedalists.rlinq");
		
		public GoldMedalists()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public GoldMedalists(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public GoldMedalists(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public GoldMedalists(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public GoldMedalists(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Goldmedalist> Goldmedalists 
		{
			get
			{
				return this.GetAll<Goldmedalist>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MySql";
			backend.ProviderName = "MySql.Data.MySqlClient";
			return backend;
		}
	}
	
	public interface IGoldMedalistsUnitOfWork : IUnitOfWork
	{
		IQueryable<Goldmedalist> Goldmedalists
		{
			get;
		}
	}
}
#pragma warning restore 1591
